-- 2022년 1월의 도서 판매 데이터
-- 저자별, 카테고리별 매출액
-- AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES

WITH SALED_ON_JAN AS (
    SELECT S.BOOK_ID, SUM(SALES) * B.PRICE AS BOOK_SALES, B.CATEGORY, B.AUTHOR_ID
    FROM BOOK_SALES S INNER JOIN BOOK B ON S.BOOK_ID=B.BOOK_ID
    WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY S.BOOK_ID, B.PRICE, B.CATEGORY, B.AUTHOR_ID
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY, SUM(S.BOOK_SALES) AS TOTAL_SALES
FROM SALED_ON_JAN S INNER JOIN AUTHOR A ON S.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY
ORDER BY A.AUTHOR_ID ASC, S.CATEGORY DESC
;
