-- 코드를 작성해주세요
WITH CHILD_DATA AS (
    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
SELECT D.ID, IF(C.CNT IS NULL, 0, C.CNT) AS CHILD_COUNT
FROM ECOLI_DATA D LEFT OUTER JOIN CHILD_DATA C ON C.PARENT_ID = D.ID
ORDER BY D.ID ASC
;