-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, SUM(SALES_AMOUNT) * PRODUCT.PRICE AS SALES
# SELECT *
FROM OFFLINE_SALE JOIN PRODUCT ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC
;
# 상품코드 별 매출액(판매가 * 판매량) 합계