-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE)
WITH AVAILABLE AS (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID NOT IN (
        SELECT DISTINCT(CAR_ID)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            TO_CHAR(END_DATE, 'YYYY-MM') = '2022-11'
            OR TO_CHAR(START_DATE, 'YYYY-MM') = '2022-11'
            OR (TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-11' AND '2022-11' <= TO_CHAR(END_DATE, 'YYYY-MM'))
    )
),

SEDAN_OR_SUV AS (
    SELECT CAR_ID, DAILY_FEE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE CAR_TYPE IN ('세단', 'SUV')
)

SELECT S.CAR_ID, S.CAR_TYPE, TRUNC(S.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100) * 30) AS FEE
FROM SEDAN_OR_SUV S INNER JOIN AVAILABLE A ON A.CAR_ID = S.CAR_ID INNER JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%'
) D ON S.CAR_TYPE = D.CAR_TYPE
WHERE 500000 <= TRUNC(S.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100) * 30)
AND TRUNC(S.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100) * 30) < 2000000
GROUP BY (S.CAR_ID, S.CAR_TYPE, S.DAILY_FEE, D.DISCOUNT_RATE)
ORDER BY FEE DESC, S.CAR_TYPE ASC, S.CAR_ID DESC
;
