-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
SELECT DISTINCT C.CAR_ID, 
       C.CAR_TYPE, 
       FLOOR(C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
       ON C.CAR_ID = H.CAR_ID 
       AND TO_CHAR(H.START_DATE, 'yyyy-mm-dd') <= '2022-11-30' 
       AND TO_CHAR(H.END_DATE, 'yyyy-mm-dd') >= '2022-11-01'
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
       ON C.CAR_TYPE = P.CAR_TYPE 
       AND P.DURATION_TYPE LIKE '30%'
WHERE H.CAR_ID IS NULL
      AND C.CAR_TYPE IN ('세단', 'SUV')
      AND C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100) * 30 >= 500000
      AND C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100) * 30 < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
