WITH MAX_FAVORITES AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI, MAX_FAVORITES MF
WHERE RI.FOOD_TYPE = MF.FOOD_TYPE AND RI.FAVORITES = MF.FAVORITES
ORDER BY FOOD_TYPE DESC
;