-- 코드를 작성해주세요
WITH SIZE_OF_TABLE AS (
    SELECT COUNT(*) AS SIZE
    FROM ECOLI_DATA
)
SELECT E.ID,
CASE
WHEN TRUNCATE((RANK() OVER (ORDER BY E.SIZE_OF_COLONY DESC)-1)/(S.SIZE/4), 0)=0 THEN 'CRITICAL'
WHEN TRUNCATE((RANK() OVER (ORDER BY E.SIZE_OF_COLONY DESC)-1)/(S.SIZE/4), 0)=1 THEN 'HIGH'
WHEN TRUNCATE((RANK() OVER (ORDER BY E.SIZE_OF_COLONY DESC)-1)/(S.SIZE/4), 0)=2 THEN 'MEDIUM'
WHEN TRUNCATE((RANK() OVER (ORDER BY E.SIZE_OF_COLONY DESC)-1)/(S.SIZE/4), 0)=3 THEN 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA E, SIZE_OF_TABLE S
ORDER BY ID ASC
;