-- 중고 거래 게시물 3건 이상 등록한 사용자
WITH ABOVE_3 AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID HAVING 3 <= COUNT(DISTINCT(BOARD_ID))
)
--  (사용자 ID, 닉네임, 전체주소, 전화번호)
SELECT USER_ID, NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS '전화번호'
FROM ABOVE_3 JOIN USED_GOODS_USER USER ON USER.USER_ID = ABOVE_3.WRITER_ID
ORDER BY USER_ID DESC
;