WITH ABOVE_3 AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID HAVING 3 <= COUNT(BOARD_ID)
)
SELECT U.USER_ID, NICKNAME, (CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2) AS 전체주소,
(SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8)) AS 전화번호
FROM ABOVE_3 A, USED_GOODS_USER U
WHERE A.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC
;