-- 중고 거래 게시물을 3건 이상 등록한 사용자
-- 사용자 ID, 닉네임, 전체주소, 전화번호를 조회하는 SQL문을 작성
WITH ABOVE_3 AS (
    SELECT COUNT(BOARD_ID) AS CNT, WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
)
SELECT U.USER_ID, U.NICKNAME, (U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2) AS "전체주소", (SUBSTR(TLNO, 0, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4)) AS "전화번호"
FROM ABOVE_3 A, USED_GOODS_USER U
WHERE A.CNT >= 3 AND A.WRITER_ID(+) = U.USER_ID
ORDER BY U.USER_ID DESC
;