-- 서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수를 조회
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, NUMBER(ROUND(AVG(r.REVIEW_SCORE), 3), 2) AS SCORE
FROM REST_INFO i INNER JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID AND i.ADDRESS LIKE '서울특별시%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC
;