-- 평균 대여 기간이 7일 이상인 자동차들의 자동차 ID와 평균 대여 기간(컬럼명: AVERAGE_DURATION) 리스트
WITH AVG_RENTAL_DAY AS (
    SELECT ROUND(AVG(END_DATE - START_DATE + 1), 1) AS AVG_DAY, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    GROUP BY CAR_ID
)

SELECT CAR_ID, AVG_DAY AS AVERAGE_DURATION
FROM AVG_RENTAL_DAY A
WHERE 7 <= A.AVG_DAY
ORDER BY AVG_DAY DESC, CAR_ID DESC
;
