-- 코드를 입력하세요
# 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수
WITH SIGNED_2021 AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
# 소수점 두번째자리에서 반올림
SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, COUNT(DISTINCT o.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT(o.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE o JOIN SIGNED_2021 u ON u.USER_ID = o.USER_ID
GROUP BY YEAR(sales_date), MONTH(sales_date)
# 년 오름, 월 오름
ORDER BY YEAR, MONTH
;