-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)을 년, 월 별로 출력
WITH COUNT_JOIN_2021 AS (
    SELECT COUNT(USER_ID) AS TOTAL
    FROM USER_INFO
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)
SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR, TO_CHAR(O.SALES_DATE, 'MM')+0 AS MONTH, COUNT(DISTINCT(U.USER_ID)) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT(U.USER_ID)) / (SELECT TOTAL FROM COUNT_JOIN_2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O LEFT OUTER JOIN USER_INFO U ON O.USER_ID = U.USER_ID
AND TO_CHAR(JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM')+0
ORDER BY YEAR ASC, MONTH ASC
;