-- 코드를 입력하세요
WITH RENTAL_ING AS (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
)
SELECT DISTINCT(C.CAR_ID), DECODE (R.CAR_ID, NULL, '대여 가능', '대여중') AS AVAILABILITY  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C, RENTAL_ING R
WHERE C.CAR_ID = R.CAR_ID(+)
ORDER BY C.CAR_ID DESC
;