-- 헤비 유저가 등록한 공간의 정보를 아이디 순
WITH ABOVE_2 AS (
SELECT HOST_ID
FROM PLACES
GROUP BY HOST_ID HAVING 2 <= COUNT(*)
)
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P LEFT OUTER JOIN ABOVE_2 A ON P.HOST_ID = A.HOST_ID
WHERE A.HOST_ID IS NOT NULL
ORDER BY P.ID ASC
;