-- 트럭
WITH DISCOUNT_PER AS (
    SELECT REPLACE(DURATION_TYPE, '일 이상', '') AS DAY, DISCOUNT_RATE AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
RENTAL_DATE AS (
    SELECT H.HISTORY_ID, C.CAR_ID, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DIFF, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT R.HISTORY_ID, TRUNCATE(CASE
    WHEN 90 <= R.DIFF
    THEN R.DAILY_FEE * (1 - (SELECT RATE FROM DISCOUNT_PER WHERE DAY = 90)/100) * R.DIFF
    WHEN 30 <= R.DIFF
    THEN R.DAILY_FEE * (1 - (SELECT RATE FROM DISCOUNT_PER WHERE DAY = 30)/100) * R.DIFF
    WHEN 7 <= R.DIFF
    THEN R.DAILY_FEE * (1 - (SELECT RATE FROM DISCOUNT_PER WHERE DAY = 7)/100) * R.DIFF
    ELSE R.DAILY_FEE * R.DIFF
    END, 0)
    AS FEE
FROM RENTAL_DATE R
ORDER BY FEE DESC, R.HISTORY_ID DESC
;