-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트
-- CAR_RENTAL_COMPANY_CAR 
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN 

WITH TRUCK_HISTORY AS (
    SELECT H.HISTORY_ID, H.CAR_ID,
        TO_CHAR(H.START_DATE, 'YYYY-MM-DD') AS START_DATE,
        TO_CHAR(H.END_DATE, 'YYYY-MM-DD') AS END_DATE,
        H.END_DATE - H.START_DATE + 1 AS DAYS,
        T.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H INNER JOIN (
        SELECT CAR_TYPE, DAILY_FEE, CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE='트럭'
    ) T
    ON H.CAR_ID = T.CAR_ID
),

TRUCK_DISCOUNT AS (
    SELECT DURATION_TYPE, DISCOUNT_RATE AS R
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

-- 대여 기록 ID와 대여 금액 리스트
SELECT H.HISTORY_ID, CASE
WHEN 90 <= DAYS THEN TRUNC(H.DAILY_FEE * (1 - (SELECT R FROM TRUCK_DISCOUNT WHERE DURATION_TYPE LIKE '90%') / 100) * DAYS)
WHEN 30 <= DAYS THEN TRUNC(H.DAILY_FEE * (1 - (SELECT R FROM TRUCK_DISCOUNT WHERE DURATION_TYPE LIKE '30%') / 100) * DAYS)
WHEN 7 <= DAYS THEN TRUNC(H.DAILY_FEE * (1 - (SELECT R FROM TRUCK_DISCOUNT WHERE DURATION_TYPE LIKE '7%') / 100) * DAYS)
ELSE TRUNC(H.DAILY_FEE * DAYS)
END AS FEE
FROM TRUCK_HISTORY H
ORDER BY FEE DESC, HISTORY_ID DESC
;