-- 자동차 타입별 할인률
WITH D AS (
    SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
T AS (
    SELECT C1.CAR_ID, C1.START_DATE, C1.END_DATE, C2.CAR_TYPE, C1.END_DATE - C1.START_DATE + 1 AS DATEDIFF, C1.HISTORY_ID, C2.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1, CAR_RENTAL_COMPANY_CAR C2
    WHERE C1.CAR_ID = C2.CAR_ID AND C2.CAR_TYPE = '트럭'
)
SELECT HISTORY_ID, CASE
    WHEN 90 <= DATEDIFF
    THEN DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM D WHERE DURATION_TYPE LIKE '90%') / 100) * DATEDIFF
    WHEN 30 <= DATEDIFF
    THEN DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM D WHERE DURATION_TYPE LIKE '30%') / 100) * DATEDIFF
    WHEN 7 <= DATEDIFF
    THEN DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM D WHERE DURATION_TYPE LIKE '7%') / 100) * DATEDIFF
    ELSE DAILY_FEE * DATEDIFF
    END AS FEE
FROM T
ORDER BY FEE DESC, HISTORY_ID DESC
;