WITH JULY_SUM AS (
    SELECT SUM(TOTAL_ORDER) AS `TO`, FLAVOR
    FROM JULY
    GROUP BY FLAVOR
),
HALF_SUM AS (
    SELECT SUM(TOTAL_ORDER) AS `TO`, FLAVOR
    FROM FIRST_HALF
    GROUP BY FLAVOR
)
-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛
SELECT J.FLAVOR
FROM JULY_SUM J JOIN HALF_SUM H ON J.FLAVOR = H.FLAVOR
GROUP BY J.FLAVOR
ORDER BY J.TO+H.TO DESC
LIMIT 3
;