-- FIRST_HALF : 상반기 주문 정보
-- JULY: 7월 아이스크림 주문 정보
WITH ORDERS_SUM AS (
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER) AS T
    FROM JULY J, FIRST_HALF F
    WHERE J.FLAVOR = F.FLAVOR
    GROUP BY J.FLAVOR
    ORDER BY T DESC
)
SELECT FLAVOR
FROM ORDERS_SUM
WHERE ROWNUM <= 3
;