-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
    INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO
        AND A.MCDP_CD = 'CS'
        AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
        AND A.APNT_CNCL_YN = 'N'
    INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD ASC
;