-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a INNER JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID AND TO_CHAR(a.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' AND a.MCDP_CD = 'CS' AND a.APNT_CNCL_YN = 'N'
    INNER JOIN PATIENT p ON p.PT_NO = a.PT_NO
ORDER BY a.APNT_YMD ASC
;