-- 코드를 입력하세요
WITH not_cancelld_appointment AS (
    SELECT APNT_YMD, APNT_NO, PT_NO, MDDR_ID
    FROM APPOINTMENT
    WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13 AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS'
)
SELECT N.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, N.APNT_YMD
FROM not_cancelld_appointment N
    JOIN DOCTOR D ON N.MDDR_ID = D.DR_ID
    JOIN PATIENT P ON P.PT_NO = N.PT_NO
ORDER BY N.APNT_YMD ASC
;