-- 코드를 작성해주세요
WITH MAKE_FRONT_CODE AS (
    SELECT SUM(CODE) AS FRONT_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, MAKE_FRONT_CODE F
WHERE D.SKILL_CODE & F.FRONT_CODE
ORDER BY D.ID ASC
;