-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람
WITH ABOVE_70 AS (
    SELECT WRITER_ID, SUM(PRICE) AS PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID HAVING 700000 <= PRICE
)
SELECT ABOVE_70.WRITER_ID, USED_GOODS_USER.NICKNAME, ABOVE_70.PRICE
FROM ABOVE_70 JOIN USED_GOODS_USER ON ABOVE_70.WRITER_ID = USED_GOODS_USER.USER_ID
ORDER BY ABOVE_70.PRICE ASC 
;