-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
WITH GET_SUM AS (
    SELECT WRITER_ID, SUM(PRICE) AS SUM
    FROM USED_GOODS_BOARD UGB
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)

SELECT U.USER_ID, U.NICKNAME, S.SUM AS TOTAL_SALES
FROM GET_SUM S, USED_GOODS_USER U
WHERE 700000 <= S.SUM
AND S.WRITER_ID = U.USER_ID(+)
ORDER BY TOTAL_SALES ASC
;