-- 
WITH ABOVE_70 AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID HAVING 700000 <= SUM(PRICE)
)
SELECT U.USER_ID AS USER_ID, NICKNAME, TOTAL_SALES
FROM ABOVE_70 A, USED_GOODS_USER U
WHERE A.WRITER_ID = U.USER_ID
ORDER BY TOTAL_SALES
;