-- MEMBER_PROFILE와 REST_REVIEW 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
WITH MOST_CNT AS (
    SELECT MAX(CNT) AS MAX
    FROM (
        SELECT COUNT(MEMBER_ID) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
)
, MOST_REVIEWING_MEMBER AS (
    SELECT COUNT(MEMBER_ID) AS CNT, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MOST_REVIEWING_MEMBER M INNER JOIN MOST_CNT C ON M.CNT = C.MAX
INNER JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
INNER JOIN MEMBER_PROFILE P ON P.MEMBER_ID = M.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC
;