-- 코드를 작성해주세요
SELECT ID, GENOTYPE, (SELECT ED2.GENOTYPE FROM ECOLI_DATA ED2 WHERE ED2.ID=ED1.PARENT_ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA ED1
WHERE GENOTYPE & (SELECT ED2.GENOTYPE FROM ECOLI_DATA ED2 WHERE ED2.ID=ED1.PARENT_ID) = (SELECT ED2.GENOTYPE FROM ECOLI_DATA ED2 WHERE ED2.ID=ED1.PARENT_ID)
ORDER BY ID ASC
;