-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트
WITH RENTALED_ABOVE_5 AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-08' <= TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

-- CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 월을 기준으로 오름차순 정렬
-- 자동차 ID를 기준으로 내림차순 정렬

SELECT TO_CHAR(H.START_DATE, 'MM') + 0 AS MONTH, H.CAR_ID AS CAR_ID, COUNT(H.CAR_ID) AS RECORDS
FROM (
    SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE '2022-08' <= TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10' 
) H INNER JOIN RENTALED_ABOVE_5 A ON H.CAR_ID = A.CAR_ID
GROUP BY TO_CHAR(H.START_DATE, 'MM'), H.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC
;
