-- 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들
-- 월별 자동차 ID 별 총 대여 횟수
WITH ABOVE_5 AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-11-01'
    GROUP BY CAR_ID HAVING 5 <= COUNT(*)
)
SELECT MONTH(START_DATE) AS MONTH, C.CAR_ID, COUNT(C.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C LEFT OUTER JOIN ABOVE_5 A ON A.CAR_ID=C.CAR_ID
WHERE A.CAR_ID IS NOT NULL AND START_DATE BETWEEN '2022-08-01' AND '2022-11-01'
GROUP BY C.CAR_ID, MONTH
ORDER BY MONTH ASC, C.CAR_ID DESC
;