-- 코드를 입력하세요
WITH A AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE '2022-08' <= TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
    GROUP BY CAR_ID HAVING 5 <= COUNT(*)
)
SELECT TO_NUMBER(TO_CHAR(C.START_DATE, 'MM')) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM A, CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE A.CAR_ID = C.CAR_ID AND '2022-08' <= TO_CHAR(C.START_DATE, 'YYYY-MM') AND TO_CHAR(C.START_DATE, 'YYYY-MM') <= '2022-10'
GROUP BY TO_NUMBER(TO_CHAR(C.START_DATE, 'MM')), C.CAR_ID
ORDER BY MONTH ASC, C.CAR_ID DESC
;