-- 자동차 종류가 '세단'인 자동차들 중 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트를 출력
WITH SEDAN_ID AS (
    SELECT CAR_ID, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
)

SELECT DISTINCT(S.CAR_ID) AS CAR_ID
FROM SEDAN_ID S, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE TO_CHAR(H.START_DATE, 'MM') = '10' AND S.CAR_ID = H.CAR_ID
ORDER BY CAR_ID DESC
;