-- 자동차 종류가 '세단'인 자동차들
-- 10월에 대여를 시작
SELECT DISTINCT(C1.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C1, CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
WHERE C1.CAR_TYPE = '세단' AND C1.CAR_ID = C2.CAR_ID AND TO_CHAR(C2.START_DATE, 'MM') = '10'
ORDER BY C1.CAR_ID DESC
;