-- 코드를 작성해주세요
WITH MAX_LENGTH AS (
    SELECT MAX(LENGTH) AS LEN, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM MAX_LENGTH ML, FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE ML.FISH_TYPE = FI.FISH_TYPE AND ML.LEN = FI.LENGTH
ORDER BY FI.ID ASC
;