WITH SALES_ON_202201 AS (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
)
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM SALES_ON_202201 S, BOOK B
WHERE S.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
;