-- FOOD_PRODUCT 테이블에서 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름을 조회
WITH MAX_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F INNER JOIN MAX_PRICE M ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.MAX
ORDER BY F.PRICE DESC
;