-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름
WITH MOST_EXPENSIVE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F LEFT OUTER JOIN MOST_EXPENSIVE M ON F.CATEGORY=M.CATEGORY
WHERE M.CATEGORY IS NOT NULL AND F.PRICE=M.MAX_PRICE
ORDER BY F.PRICE DESC
;